### ISSUE TITLE
"FR" Lizenzänderung

### ISSUE THREAD

**Issue by zonky2** [byteworks-ch/contao-metamodelsattribute_multi#1]
Hallo Michael,

leider steht in den Quelltexten "All rights reserved", so dass eine Nutzung oder Einbindung in MetaModels bzw. in eigene Projekte nicht möglich ist - schade :-(

Wäre es möglich die Lizenzbedingungen auf eine weniger restriktive Variante z.B. MIT, LGPL o.ä. zu wechseln?

Gruss zonky

**Comment by micbis** [comment]
Lizenz wurde auf GPL geändert.

**Comment by zonky2** [comment]
prima!

**Comment by zonky2** [comment]
Hinweis: die serialisierten Arrays werden in MM als BLOB gespeichert

 

Von: Michael Bischof [mailto:notifications@github.com] 
Gesendet: Freitag, 8. April 2016 16:56
An: byteworks-ch/contao-metamodelsattribute_multi
Cc: zonky2
Betreff: Re: [byteworks-ch/contao-metamodelsattribute_multi] "FR" Lizenzänderung (#1)

 

Lizenz wurde auf GPL geändert.

**Comment by micbis** [comment]
Auf BLOB geändert.
