### ISSUE TITLE
Update für MM 2.0.0

### ISSUE THREAD

**Issue by zonky2** [byteworks-ch/contao-metamodelsattribute_multi#2]
für die Zusammenarbeit mit dem aktuellen MM Update für MM 2.0.0 a10 müssten folgende Sachen geändert werden:

1. sortable und flag entfernen in https://github.com/byteworks-ch/contao-metamodelsattribute_multi/blob/master/src/system/modules/metamodelsattribute_multi/dca/tl_metamodel_dcasetting.php#L31-L32
2. MCW als required in der composer.json https://github.com/byteworks-ch/contao-metamodelsattribute_multi/blob/master/composer.json#L20

wenn das geändert ist, würde ich eine kurze Anleitung im Bereich "Kochbuch" des Handbuches schreiben...

Gruss

**Comment by micbis** [comment]
Ist gemacht.

**Comment by zonky2** [comment]
o.k. - teste ich nochmal..

Dank!

**Comment by zonky2** [comment]
@micbis habe das Paket nochmal per Composer installiert - soweit alles o.k.... man muss aber auf "dev" schalten, damit die neueste Version gezogen wird => vielleicht kannst Du die Version bei Gelegenheit "tagen"

**Comment by micbis** [comment]
Danke fürs Feedback. Ist getagged: 1.0.1

**Comment by zonky2** [comment]
?? die neue Version hätte m.E. 1.0.4 bekommen müssen - Du standest doch auf 1.0.3 ...

**Comment by zonky2** [comment]
bitte "tagging" nochmal prüfen

ggf. auf Startseite verlinken nach http://metamodels.readthedocs.org/de/latest/cookbook/extensions/attribute_mcw.html
